### ISSUE TITLE
Excluding Dolby Vision/HDR doesn't work

### ISSUE THREAD

**Issue by barronen1** [Tikipeter/repository.tikipeter#117]
Hi,

Kodi version: 19.5
Fen version: 3.0.36
Metadata langauge in fen settings: Hebrew

My fen results is configured like this:
![image](https://user-images.githubusercontent.com/29895680/213884445-d21f5a1b-2514-43ee-9ea1-54ae77925f5d.png)

But I still get links for HDR / Dolby vision.

kodi.log on DEBUG mode provided. playing in Fen with RD - She hulk episode 01 DOVI file.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/10472904/kodi.log)

Examples:
Dolby Vision:
![image](https://user-images.githubusercontent.com/29895680/213884492-2d1059d1-7f5f-44fe-8a4c-efd6998e614a.png)

HDR:
![image](https://user-images.githubusercontent.com/29895680/213884496-982ea751-45fb-40e3-91dd-33e368ffaeb0.png)

**Comment by ambulancePilot** [comment]
Have you cleared the scraper cache after changing settings to exclude HDR and DV?

**Comment by barronen1** [comment]
> Have you cleared the scraper cache after changing settings to exclude HDR and DV?

How do you mean? But anyway the problem persists even after several Kodi restarts with the settings configured already.

**Comment by ambulancePilot** [comment]
The problem will persist if you have not cleared the scraper cache regardless of how many times you set the settings and restart Kodi.

Go into Fen -> Tools -> Clear Databases and Clean Settings Files -> Clear External Scrapers Cache

The above needs to be done **after** you change the exclusion settings.

**Comment by barronen1** [comment]
I’ve done exactly as you said, but no changes. Same results as in the pictures above

**Comment by ambulancePilot** [comment]
I don't have this issue. All DV and HDR files are excluded for me, and the only thing I can think of is you have AV1 files included.

I don't know much about encoding, but my understanding was that AV1 includes some types of HDR, so you will have those slip through the cracks if you disable HDR but enable AV1 (I think). AV1 is also not supported in Kodi unless you are using Nexus.

Question: after doing what I suggested above (clearing cache), did the DV file get excluded? If yes, then your problem is the inclusion of AV1 files.

**Comment by Tikipeter** [comment]
You shouldn't need to clear the scraper caches to get immediate results. The filtering is done on the fly.

I'll look into this. I'm just short on time currently.

**Comment by Tikipeter** [comment]
For my benefit when I have some time to get to this issue: install is on a Windows machine, not Arch Linux like I was hoping.

**Comment by barronen1** [comment]
Note: also happens to me on Android TV

**Comment by Tikipeter** [comment]
Cocoscrapers issue unfortunately.

I will let the Cocoscrapers dev know about it.

**Comment by barronen1** [comment]
Thank you,
Feel free to update here if it get fixed

**Comment by Tikipeter** [comment]
I'll add workarounds for now....

**Comment by barronen1** [comment]
Hi, did it got fixed in a new update?
And if possible can you describe how you fixed the hdr/dv exclusion? if the issue is in Cocoscrapers

**Comment by Tikipeter** [comment]
It should be working in the latest update, but you tell me....

The issue is Cocoscrapers is meant to return the string we use to filter formatted like this: '4k.hdr.dd.releasegroup.etc`, but on some scrapers it is returning this instead: `4khdrddreleasegroupetc` which screws up some of the filters. I added some extra terms to the filters to get around this for now, but it needs to be fixed if I can ever get in contact with the CCS dev...

**Comment by barronen1** [comment]
Hi, I’ve tested it and from what it seems.

* HDR Exlcuding works. 

* Dolby Vision works for most cases, but sometimes I do see some DV links. 

Do you want me to provide you kodi.log on debug?

**Comment by barronen1** [comment]
@Tikipeter

**Comment by TwillightMercy** [comment]
Hi @Tikipeter ,

HDR exclude works now.

It seems that DV exclusion still doesn't work. debug log:

https://paste.kodi.tv/bomujuhuxi
