### ISSUE TITLE
Random (possibly Fen) errors

### ISSUE THREAD

**Issue by Ade-AV** [Tikipeter/repository.tikipeter#149]
Hi

I'm using Arctic Horizon 2 on Apple TV and every now and then it will present with a 'Fen Error' and the widget(s) will not load

In this example I had to restart the Apple TV after it was hanging when trying to 'Quit' Kodi, after restarting it showed a 'Fen Error' and the first widget (Fen TV Next Episodes) did not load 

https://paste.kodi.tv/etapujeguj

**Comment by Tikipeter** [comment]
AppleTV issue.

Sometimes it is unable to access a plugin's settings file on startup.

**Comment by Ade-AV** [comment]
Thanks, is there any way it can be fixed? And is there an easy way to recover when it happens?

**Comment by Tikipeter** [comment]
I'll have a good think about it. There was another issue like this a few months ago, and it was resolved with some changes I made. Unfortunately, I cannot remember what those changes were.

https://github.com/Tikipeter/repository.tikipeter/issues/51

Whilst I think on this, there is some testing you could do if able. Firstly, remove all Fen widgets from the homescreen. Restart Kodi, and attempt to navigate into the Fen settings. If all settings are present and correct, that is a good sign at least. Navigate through Fen and keep an eye out for any errors appearing.

There are definitely some issues with your log, of which what might be the main issue is something I don't see being able to do anything about. Kodi's `CAddonMgr` starts briskly after Kodi loads (`~.350sec` after Kodi start), but the `services` of addons are VERY slow to start. Well over 1 second until Fen's services module is even loaded into cache, and then another 6 seconds (wow) until the services start running.

Fen needs those services to run much earlier than 7 seconds, as widgets are already trying to load by that point.

I will have a good think about this, and try to allow the things I need to do at startup to fail in a better way. But sometimes things just NEED to be done.

I'll do my best......

**Comment by Ade-AV** [comment]
Disabled (not deleted) all home screen widgets, hung on 'Quit' so had to Restart Apple TV, Fen Settings all seem ok, moved around through Fen and all ok until TV Next Episodes where I got an error

https://paste.kodi.tv/ivuyehopiy

**Comment by Tikipeter** [comment]
Next update will hopefully have a workaround for this issue.

Until then, it is strongly advised to DISABLE Fen and restart Kodi. Use another addon until after the update.

I will let you know here when the update has been uploaded to the repo.

**Comment by Tikipeter** [comment]
Latest version `3.0.43` uploaded.

**Comment by Ade-AV** [comment]
Thanks for working on this, overall it seems to be better but still getting the occasional error, in this example it let me 'Quit' out of Kodi and then an error on restart 

https://paste.kodi.tv/kalomamati

**Comment by Tikipeter** [comment]
Might b due to the fairly new sys exit command when dealing with items on the home screen. To fix the language invoker bug.

I've added a 30 second delay before that starts being used for next update.

**Comment by Ade-AV** [comment]
Hi

Still getting errors

https://paste.kodi.tv/zisoxiwoxe
