### ISSUE TITLE
Fen not showing Debrid cloud sources

### ISSUE THREAD

**Issue by ShibajiCh** [Tikipeter/repository.tikipeter#634]
Hi @Tikipeter,

I'm using Kodi v19.3 on Nvidia shield tv pro. After the latest Fen update to v2.5.06 I'm not able to see any of my Real Debrid cloud sources after scraping. Also the number of other torrent sources being shown are comparatively less than before. I've enabled all torrent sources in Fenom scrapers and also re-authenticated Real Debrid. The settings are also fine. Still the same issue is happening. Fenom scrapers version is also up to date i.e.v1.5.9. Could you please look into the issue and let me know your feedback?

Here's my log:

https://paste.kodi.tv/akepikibin.kodi

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
No idea. Nothing in the log.
Delete `providerscache.db`, restart Kodi, and try again.

**Comment by Tikipeter** [comment]
Might be worth uninstalling Fen & FenomScrapers and then reinstalling Fen.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I deleted providerscache.db and also uninstalled and reinstalled Fen and Fenom scrapers but still I'm facing the same issue. No debrid cloud sources are showing up. Are you not facing this issue at your end?

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I checked again thoroughly and identified a few things. Some cloud sources are showing up, for example Castle Rock, Doom Patrol, The Walking Dead, etc. However, others like Gunpowder Milkshake, Hitman's Wife's Bodyguard, Escape Room 2, The Forever Purge, etc. are not showing up. So I guess something is wrong with the search parameter maybe. This is just my observation. You might be able to understand better. Earlier this issue was not there. Please advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
I've recently noticed more issues with parsing results filenames like HDR etc. I'd set those to "Include" and see if that brings back the missing sources. I'm thinking they may be incorrectly being tagged as HDR, DV etc and are getting filtered out.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I've included HDR and Dolby Vision sources as Prefer (Autoplay) in settings, but still I'm not able to see those specific cloud sources.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I noticed one more thing that in Fen Settings - > Results - > Results Display, the images are not showing anymore. Just wanted to let you know.

See screenshot below:
![IMG20211111014812](https://user-images.githubusercontent.com/65297828/141187205-0ec67db0-676d-4efc-b1ad-238247a231db.jpg)

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
![screenshot00000](https://user-images.githubusercontent.com/28930002/141188619-bf39dbfc-79e1-429e-a4ab-904b41d1cfaa.png)

There's definitely something wrong with your install. Is that skin Arctic Zephyr? I might install it to make sure it's not the skin messing things up somehow. Don't know how though.

Give me one filename of an example of something in your Cloud not scraping. Does Fen find the file, but then does not display it? Or does it just not find it at all?

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

The skin is Arctic Horizon by jurialmunkey and it got updated today as well. Few files which are not showing up as debrid cloud sources are as follows:

Gunpowder.Milkshake.2021.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT.mkv

The.Hitmans.Wifes.Bodyguard.2021.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.7.1-FGT.mkv

Californication.S01.1080p.BluRay.X264-CLASSiC[rartv]

Escape.Room.Tournament.of.Champions.2021.2160p.WEB-DL.x265.10bit.HDR.DD5.1-CM

The.Protege.2021.1080p.AMZN.WEBRip.DDP2.0.x264-LUT

Cruella.2021.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.x265-MZABI

Please check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
![screenshot00001](https://user-images.githubusercontent.com/28930002/141190515-867c45ed-e0ea-4976-ac38-aafeb44e9ed5.png)

Just checked and I am getting Cloud sources found as well.

I'll check out those names. Thanks for that.

RD for your cloud source?

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

You're welcome!
Yes, RD is my cloud source.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
![screenshot00002](https://user-images.githubusercontent.com/28930002/141191267-67ff9b62-3943-4c20-a1b0-e23adc9ce9fc.png)

I tried with `The.Protege.2021.1080p.AMZN.WEBRip.DDP2.0.x264-LUT`.
Added it to all three clouds (RD, PM, AD). The PM and AD results showed, but not the RD. Which is good news because now I can track down the issue.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

OK great. Thanks for letting me know! Looking forward to your update regarding what is causing the issue.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Found the issue.
Hopefully I'll have an update ready in about 24 hours. There's other things to fix.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

OK great! Thanks! Looking forward to the next update. I also switched to the default Estuary skin still the images under Fen Settings - > Results - > Results Display, are not showing up. Is it related to the issue that you found out? Kindly advise.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
No. But when replying to you I just realized why that issue is happening as well. :)

I thought I pushed an update to `script.tikiart` which included changes to make those images continue to show, but upon checking the zip on github it doesn't have those changes. So apparently I've been the only one able to see those images since probably 2.5.01!

That will be sorted in 24 hours too.

**Comment by Tikipeter** [comment]
Still don't know why you're not getting the same number of results as before. But wait until the next update and see if anything I've changed helps with that.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

OK good to hear that. Thanks a lot! I'll be checking the next update and let you know if all issues are resolved.

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

After installing the latest Fen update v2.5.07 majority of the debrid cloud sources are working fine now. However, a few debrid cloud sources like the following TV show pack is still not showing up even after re-scraping:

Californication.S01.1080p.BluRay.X264-CLASSiC[rartv]

Could you please look into the issue and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

I installed the latest Fen update v2.5.08, even then a few debrid cloud sources like the following TV show pack is still not showing up after re-scraping:

Californication.S01.1080p.BluRay.X264-CLASSiC[rartv]

Could you please check and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
I'm not sure of the issue now.
It scrapes for me using 2.5.08....
I added `cls` to the `unwanted_tags` list, which means it shows now whether title check is on or off for me.

![screenshot00000](https://user-images.githubusercontent.com/28930002/141593995-1468a857-8a5f-4154-b48c-97b76935b0b5.png)

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Thank you! However, the file mentioned in your screenshot is not exactly the one which I mentioned above. As you can see the one showing in your screenshot is from an SD 480p source, whereas the one I mentioned is from a full HD 1080p source. Also this one which you're seeing is not from the debrid cloud but a cached one. Here's the file name again for your reference:

Californication.S01.1080p.BluRay.X264-CLASSiC[rartv]

I'm not sure if anything can be done to resolve this issue but just wanted to let you know. Kindly let me know your feedback.

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
That's what the files inside that torrent are titled. The file in the pic is from that source. It is 2.18 Gig, so definitely not a 480p file.

Have you looked inside that torrent to see how the files are named?

**Comment by ShibajiCh** [comment]
Hi @Tikipeter,

Apologies, I didn't check the content inside the pack and was simply checking the scraping results by name. Actually I had both the HD and SD packs added in my Debrid cloud for testing purpose. Hence, the confusion. Yes, the naming convention of the file pack was absolutely incorrect. However, the actual files inside the pack were in 1080p. Thanks for your support! All other files are scraping fine now. I think the issue is fixed. You can close this issue ticket if you want. Thanks a lot again!

Thanks and Regards,
ShibajiCh.

**Comment by Tikipeter** [comment]
Good to hear it's sorted. 👍

**Comment by ShibajiCh** [comment]
> Good to hear it's sorted. 👍

Hi @Tikipeter,

Thank you so much! 🙂

Thanks and Regards,
ShibajiCh.
