### ISSUE TITLE
[Arch Linux] Fen + Python 3.10 = Kodi Crashes

### ISSUE THREAD

**Issue by pc-2198x** [Tikipeter/repository.tikipeter#661]
**Describe the bug**

Python got updated from 3.9 to 3.10 via `pacman` on Arch Linux. This causes Kodi to immediately crash if Fen in installed. I uninstalled Kodi, cleaned up all remaining config. Performed a clean install of Kodi. Crashed immediately after re-installing Fen.

**Log**

The crash log references `/usr/lib/python3.10/sqlite3/dbapi2.py` and points to timestamp conversions as the culprit.

[kodi_crashlog-20211216_223049.log](https://github.com/Tikipeter/repository.tikipeter/files/7731914/kodi_crashlog-20211216_223049.log)

**To Reproduce**

1. Clean install Kodi on Arch Linux running newest Python 3.10.
2. Install Fen.
3. Crashes immediately.

**Expected behavior**

1. Clean install Kodi on Arch Linux running newest Python 3.10.
2. Install Fen.
3.  Configure and use Fen without crashing.

**Environment**

`uname -a`:
```
Linux GigaArch 5.15.8-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 14 Dec 2021 12:27:58 +0000 x86_64 GNU/Linux
```

`kodi -v`:
```
19.3 (19.3.0) Git:20211203-nogitfound Media Center Kodi
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv
```
Latest Fen - 2.5.15

**Comment by Tikipeter** [comment]
I'm at work at the moment, but I'm not sure what exactly I could do about this. There's been rumblings for a while now that the Arch Python 3.10  update is garbage.

**Comment by pc-2198x** [comment]
Yes unfortunately it appears to have caused quite a number of things to break, including other addons. Just wanted to make you aware since I didn't see a bug report about it.

**Comment by Tikipeter** [comment]
OK. Thanks for that. If you can get a hold of an older version of the offending packages, or install 3.9 and point Kodi at that version, it might be your best bet.

**Comment by pc-2198x** [comment]
Alright I will look into that, thanks

**Comment by pc-2198x** [comment]
Update for anyone else having this issue - downgrading from Python `3.10.1.1` to `3.10.0.1` allows Fen to continue to function normally. Downgrade and add `python` to your `ignore` list in `pacman.conf` until this issue is corrected on the Python side.

**Comment by ReaLx3m** [comment]
Since i ran into the same issue with python on arch based distro(Manjaro), heres a quick(dirty) fix for it in case anyone stumbles upon this post. 
You need to edit:
/usr/lib/python3.10/sqlite3/dbapi2.py
Lines 80-83:
register_adapter(datetime.date, adapt_date)
register_adapter(datetime.datetime, adapt_datetime)
register_converter("date", convert_date)
register_converter("timestamp", convert_timestamp)

And comment them out by adding # in front of each line.
So far havent noticed any other adverse effects because of this modification.

**Comment by marathone** [comment]
Got a debug log for two add-ons that are screwed with Python 3.9.10 (C:\GoTo and Cumination). _Seems to be when trying to format date from its sqlite3 cache_. Anyway attaching debug:
[gdb.log](https://github.com/Tikipeter/repository.tikipeter/files/7947015/gdb.log)

**Comment by marathone** [comment]
/usr/lib/python3.10/sqlite3/dbapi2.py Lines 80-83: register_adapter(datetime.date, adapt_date) register_adapter(datetime.datetime, adapt_datetime) register_converter("date", convert_date) register_converter("timestamp", convert_timestamp)

I can confirm that this fixes 'Cumination' on Debian SID, but GoTo still doesn't, just throws an error when selecting a submenu item. 
I'll logout and see if it makes any difference, probably won't.
